Adding sectioned up happiness metric + fixing healthHappiness
nkremerh/sugarscape pull request #24
Opened 2024-01-30 21:40 UTC by mmilkowski36

2024-02-06 22:36 UTC, hadiyachishti reviewed
👍

2024-02-09 04:44 UTC, nkremerh requested changes

2024-02-09 04:44 UTC, nkremerh commented on sugarscape.py
> +                             "totalMetabolismCost": 0, "agentReproduced": 0, "agentStarvationDeaths": 0, "agentDiseaseDeaths": 0, "environmentWealthCreated": 0,
Trailing whitespace.

2024-02-09 04:44 UTC, nkremerh commented on sugarscape.py
> +                             "meanSocialHappiness": 0, "meanFamilyHappiness": 0, "meanConflictHappiness":0, "meanAgeAtDeath": 0, "seed": self.seed, "totalWealthLost": 0,
meanConflictHappiness value should have space after colon.
Trailing whitespace at end of line.

2024-02-09 04:44 UTC, nkremerh commented on agent.py
> +        else: return 0
Put return on next line.

2024-02-09 04:44 UTC, nkremerh commented on agent.py
> +        if self.isSick(): return -1
Put return on next line.

2024-02-09 04:44 UTC, nkremerh commented on agent.py
>          else: return 1
Put return on next line.

2024-02-09 04:44 UTC, nkremerh commented on agent.py
> +        return self.wealthHappiness
Should return calculated value, not a data member.

2024-02-09 04:45 UTC, nkremerh commented
Only nitpicks left here. Good work!

2024-02-09 17:23 UTC, nkremerh commented
Added patch on those nitpicks. Please test and let me know if everything still behaves as intended. Revert anything that I broke!

2024-02-12 21:44 UTC, nkremerh approved these changes

2024-02-12 21:45 UTC, merged