Modifies loops to use .items()
nkremerh/sugarscape pull request #90
Opened 2024-06-27 08:53 UTC by amuller26

Also simplified three three loops in agent.py

2024-06-27 16:26 UTC, nkremerh commented
@colinhanrahan Review, please.

2024-06-28 01:58 UTC, colinhanrahan requested changes

2024-06-28 01:58 UTC, colinhanrahan commented on sugarscape.py
> +            for config in configurations.items():
I think `.values()` is a better fit here. With `.items()`, you're setting `config` to a tuple of the key (the name of the config option) and the value (the sub-dictionary with `"endowments"` etc.). `.values()` will let you access just the values, which in this case is the sub-dictionary you're currently accessing with `config[1]`. So it should look something like `for config in configurations.values(): config["endowments"].append(...)`.

2024-06-28 17:23 UTC, nkremerh commented on agent.py
> +        for cell in  self.cell.neighbors.values():
There's an extra space after `in` on this line.

2024-06-28 18:15 UTC, nkremerh commented
This should a separate branch from your master as you will get a merge conflict when I do a squash and merge of this PR. Your master branch's history will have a few commits which will soon be squashed into one. Closing this and will wait for a new one to open from a separate branch.

2024-06-28 18:16 UTC, nkremerh commented on agent.py
> +        for cell in self.cell.neighbors.values():
On second thought, this change should be reverted. It doesn't gain us anything and incurs an extra function call without added clarity for what's happening.

2024-06-28 18:16 UTC, nkremerh commented on agent.py
> +        for cell in  self.cell.neighbors.values():
On second thought, this change should be reverted. It doesn't gain us anything and incurs an extra function call without added clarity for what's happening.

2024-06-28 18:19 UTC, closed without merging